name: Build styles and deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    env:
      NODE_ENV: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup tailwind
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Build
        run: |
          npm install -g tailwindcss-cli@2.0.4
          tailwindcss-cli build ./src/tailwind.css -o ./dist/tailwind.css

      - name: Deploy
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-north-1"
          SOURCE_DIR: "public"
